# https://docs.netlify.com/configure-builds/file-based-configuration

[build]
  base    = "docs"
  command = "yarn generate"
  publish = "dist"
  ignore  = "git diff --quiet HEAD^ HEAD . ../package.json"
