name: Reproduire

permissions:
  issues: write

on:
  issues:
    types: [labeled]


jobs:
  reproduire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: Hebilicious/reproduire@4b686ae9cbb72dad60f001d278b6e3b2ce40a9ac # v0.0.9-mp
        with:
          label: 'need reproduction' # Optional, will default to this value.
